# Generated by Django 3.2.4 on 2022-04-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220426_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
