# Generated by Django 3.2.4 on 2022-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_person_profile_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
