# Generated by Django 3.2.4 on 2022-11-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20221119_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='info')),
                ('styleId', models.TextField(max_length=10)),
            ],
        ),
    ]
