# Generated by Django 3.2.4 on 2022-11-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(max_length=1000)),
                ('rate', models.IntegerField()),
                ('icon', models.ImageField(upload_to='icon')),
            ],
        ),
    ]
