# Generated by Django 3.2.4 on 2022-11-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_skils'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skils',
            new_name='Skills',
        ),
    ]
