# Generated by Django 3.2.4 on 2022-11-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.TextField(max_length=50),
        ),
    ]
