# Generated by Django 3.2.4 on 2022-12-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_skill_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='trailer',
            new_name='link',
        ),
    ]
